### ISSUE TITLE
Please add a default .gitignore file to the generated project

### ISSUE THREAD

**Issue by GeekEast** [arco-design/arco-design-pro#10]
## Basic Info 

Please add a default `.gitignore` file to the generated project.

![image](https://user-images.githubusercontent.com/24806887/139841944-5183a58a-0c24-44a1-b501-8ee798058d9a.png)

**Comment by PengJiyuan** [comment]
Ok, get

**Comment by kirazxyun** [comment]
@GeekEast This issue is resolved in this commit. [https://github.com/arco-design/arco-design-pro/commit/d8c5c85cc060790730acf14c310b057600c99c27](commit)
