### ISSUE TITLE
文档是不是过期了?  @arco-design/web-react/Affix/style/css 无这个路径

### ISSUE THREAD

**Issue by vaynevayne** [arco-design/arco-design-pro#100]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro@2.8.0
- **Browser:** chrome110.0.0.0

**Comment by yuhan0709** [comment]
应该是 `@arco-design/web-react/es/Affix/style/css` 你说的文档地址是哪个呢，我来改下。
