### ISSUE TITLE
希望arco-design-pro支持React 17.0全新jsx转换，否则引入第三方组件无法正常编译，比如react-dnd

### ISSUE THREAD

**Issue by Tsrign** [arco-design/arco-design-pro#11]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## What are the similar cases of this feature
暂无

## What problem does this feature solve?
当尝试在arco-design-pro中使用react-dnd，执行npm run dev 遇到如下错误：
ERROR in ./node_modules/react-dnd/dist/esm/core/DndProvider.js
Module not found: Error: Can't resolve 'react/jsx-runtime' in 'arco-test/node_modules/react-dnd/dist/esm/core'

通过以下方式才得以解决，但成本较大：
1、尝试升级typescript(4 )、react(17.0.2)、react-dom(17.0.2)等
2、尝试去除arco-design-pro代码中 import React from 'react'
3、修改配置webpack.config、.babelrc、.tsconfig.json

**Comment by kirazxyun** [comment]
收到，我们探究一下如何修改～

**Comment by Tsrign** [comment]
> 收到，我们探究一下如何修改～

好的，期待解决

**Comment by lianghx-319** [comment]
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
