### ISSUE TITLE
路由权限控制有什么方式吗

### ISSUE THREAD

**Issue by lin-mt** [arco-design/arco-design-pro#12]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## What are the similar cases of this feature
类似 ant design pro 的权限控制，或者是否可以根据一个 http 请求动态生成菜单（这个我在 ant design pro 提过，没有好的解决方案就关了，现在那个 issue 还偶尔被挖出来，所以应该还是很多人希望有这个功能的。。。）

## What problem does this feature solve?
根据权限控制菜单的显示

**Comment by PengJiyuan** [comment]
我们想想

**Comment by Queensbarry** [comment]
目前通过改动 route.ts 文件中，增加 access 项目后可以在生成路由表和左侧栏时对权限进行控制，例如：
```typescript
[
  {
    name: 'menu.dashboard',
    key: 'dashboard',
    icon: <IconDashboard />,
    children: [
      {
        name: 'menu.dashboard.workplace',
        key: 'dashboard/workplace',
        componentPath: 'workplace',
      },
      {
        name: 'menu.dashboard.monitor',
        key: 'dashboard/monitor',
        componentPath: 'monitor',
        access: [isAdmin],
      },
    ],
  },
]
```

并且在 index.tsx 中完成鉴权生成带有权限的路由表和左侧菜单栏，具体代码后面看尝试着提交 pr 后官方接收否

**Comment by kirazxyun** [comment]
> 目前通过改动 route.ts 文件中，增加 access 项目后可以在生成路由表和左侧栏时对权限进行控制，例如：
> 
> ```ts
> [
>   {
>     name: 'menu.dashboard',
>     key: 'dashboard',
>     icon: <IconDashboard />,
>     children: [
>       {
>         name: 'menu.dashboard.workplace',
>         key: 'dashboard/workplace',
>         componentPath: 'workplace',
>       },
>       {
>         name: 'menu.dashboard.monitor',
>         key: 'dashboard/monitor',
>         componentPath: 'monitor',
>         access: [isAdmin],
>       },
>     ],
>   },
> ]
> ```
> 
> 并且在 index.tsx 中完成鉴权生成带有权限的路由表和左侧菜单栏，具体代码后面看尝试着提交 pr 后官方接收否

了解，我们的代码正在进行2期改造，近期会推送，请在我们正式发布后在新的代码上修改。

**Comment by Queensbarry** [comment]
> > 目前通过改动 route.ts 文件中，增加 access 项目后可以在生成路由表和左侧栏时对权限进行控制，例如：
> > ```ts
> > [
> >   {
> >     name: 'menu.dashboard',
> >     key: 'dashboard',
> >     icon: <IconDashboard />,
> >     children: [
> >       {
> >         name: 'menu.dashboard.workplace',
> >         key: 'dashboard/workplace',
> >         componentPath: 'workplace',
> >       },
> >       {
> >         name: 'menu.dashboard.monitor',
> >         key: 'dashboard/monitor',
> >         componentPath: 'monitor',
> >         access: [isAdmin],
> >       },
> >     ],
> >   },
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 并且在 index.tsx 中完成鉴权生成带有权限的路由表和左侧菜单栏，具体代码后面看尝试着提交 pr 后官方接收否
> 
> 了解，我们的代码正在进行2期改造，近期会推送，请在我们正式发布后在新的代码上修改。

明白，期待二期代码

**Comment by lin-mt** [comment]
> > > 目前通过改动 route.ts 文件中，增加 access 项目后可以在生成路由表和左侧栏时对权限进行控制，例如：
> > > ```ts
> > > [
> > >   {
> > >     name: 'menu.dashboard',
> > >     key: 'dashboard',
> > >     icon: <IconDashboard />,
> > >     children: [
> > >       {
> > >         name: 'menu.dashboard.workplace',
> > >         key: 'dashboard/workplace',
> > >         componentPath: 'workplace',
> > >       },
> > >       {
> > >         name: 'menu.dashboard.monitor',
> > >         key: 'dashboard/monitor',
> > >         componentPath: 'monitor',
> > >         access: [isAdmin],
> > >       },
> > >     ],
> > >   },
> > > ]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 并且在 index.tsx 中完成鉴权生成带有权限的路由表和左侧菜单栏，具体代码后面看尝试着提交 pr 后官方接收否
> > 
> > 
> > 了解，我们的代码正在进行2期改造，近期会推送，请在我们正式发布后在新的代码上修改。
> 
> 明白，期待二期代码

老哥，pro 2.0 上线了😄期待你的 PR

**Comment by PengJiyuan** [comment]
2.0 上线了，会持续迭代升级，马上会支持这个功能

**Comment by Queensbarry** [comment]
> 2.0 上线了，会持续迭代升级，马上会支持这个功能

pr 中尝试了一下
