### ISSUE TITLE
webpack 配置代理后路由跳转有问题

### ISSUE THREAD

**Issue by lin-mt** [arco-design/arco-design-pro#13]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## Basic Info 
- **Package Name And Version:** "@arco-design/webpack-plugin": "^1.5.2"
- **System:** mac os
- **Browser:** chrome
- **Reproduction Link:** 官方是否可以提供一个简易的 jsfiddle/codepen/codesandbox 例子，我们再根据这个例子 fork 出来重现 bug，这样会方便一点～

## What is expected?
登陆成功后，正常跳转

## Steps to reproduce
如果有登陆，先退出登陆
1. 在 webpack.config.js 添加配置
```js
  config.devServer = {
    proxy: {
      '/simpleProxy': {
        target: 'http://localhost:8080',
        changeOrigin: true,
        pathRewrite: { '^/simpleProxy': '' },
      },
    }
  }
```
2. 输入账号密码，点击登陆

![image](https://user-images.githubusercontent.com/58337359/142571825-92978ca4-7a57-42ff-b05b-b8f73009ca4a.png)

3. 浏览器重新访问 http://localhost:9090/ 后，才可以正常访问

**Comment by kirazxyun** [comment]
webpack 配置是没有问题的是跳转的路由不正确，这是个问题，我们改一下。

**Comment by zmzimpl** [comment]
> webpack 配置是没有问题的是跳转的路由不正确，这是个问题，我们改一下。

改好了吗？还是存在这个问题

**Comment by Queensbarry** [comment]
以上问题实质上是由于 history 特性造成的，history 模式不像 hash 模式，用 # 来区分前后端路由，可以增加下述两行代码避免 history 下后端代理失效（实质上是 webpack-dev-server少了配置）

```js
inline: true
historyApiFallback: true
```

webpack.config.js 该部分完整配置如下：
```js
config.devServer = {
  inline: true
  historyApiFallback: true
  proxy: {
    '/api': {
      target: 'http://localhost:8080',
      changeOrigin: true,
      pathRewrite: {
         '^/api': '' 
      },
    },
  }
}
```

**Comment by melong007** [comment]
@Queensbarry 这个可以在Arco Pro 最佳实践 加个示例？
![image](https://user-images.githubusercontent.com/1418526/147058838-243f9d7d-a4ae-4e86-9891-9f6f20bb6339.png)

**Comment by kirazxyun** [comment]
> @Queensbarry 这个可以在Arco Pro 最佳实践 加个示例？ ![image](https://user-images.githubusercontent.com/1418526/147058838-243f9d7d-a4ae-4e86-9891-9f6f20bb6339.png)

可以的，近期的版本会加上。

**Comment by BongBongBang** [comment]
> @Queensbarry 这个可以在Arco Pro 最佳实践 加个示例？ ![image](https://user-images.githubusercontent.com/1418526/147058838-243f9d7d-a4ae-4e86-9891-9f6f20bb6339.png)

大佬，您这张截图，不是官网的截图，是您自己本地的吧？

**Comment by Queensbarry** [comment]
> > @Queensbarry 这个可以在Arco Pro 最佳实践 加个示例？ ![image](https://user-images.githubusercontent.com/1418526/147058838-243f9d7d-a4ae-4e86-9891-9f6f20bb6339.png)
> 
> 大佬，您这张截图，不是官网的截图，是您自己本地的吧？

这个是 1.* 版本的时候写的了，现在应该是写在 `config-overrides.js` 中了
