### ISSUE TITLE
关于自动移除国际化

### ISSUE THREAD

**Issue by Onion17** [arco-design/arco-design-pro#37]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## 现有案例
Ant Design Pro

## 预期解决问题
希望可以通过npm命令自动移除国际化

**Comment by Przeblysk** [comment]
请问下这个feature有排期了吗😋

**Comment by yuhan0709** [comment]
这个看了下 国际化直接删代码比较简单？pro 目前如果支持基本要对整个模版进行处理，成本较大

**Comment by dingshaohua-com** [comment]
> 这个看了下 国际化直接删代码比较简单？pro 目前如果支持基本要对整个模版进行处理，成本较大

https://github.com/dingshaohua-com/arco-rm-i18n
