### ISSUE TITLE
跑不起来...

### ISSUE THREAD

**Issue by mdddj** [arco-design/arco-design-pro#40]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro@2.3.1
- **系统版本:** macos
- **浏览器版本:** chrome98.0.4758.109
- **复现地址:** 无

## 预期结果
成功创建项目.

## 复现步骤
输入
```
arco init hello-arco-pro
```
选择公共版本
提示: TypeError: Cannot read properties of undefined (reading 'public')
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/29020213/157212536-7e3ccc61-63c2-41bf-b2a6-86d63d65efa8.png">

**Comment by yuhan0709** [comment]
@MisterLuffy 哥哥看下捏～ 为什么哦

**Comment by yuhan0709** [comment]
升级一下cli版本看下呢
