### ISSUE TITLE
vite 版本没有构建生产环境的 npm script

### ISSUE THREAD

**Issue by chenc041** [arco-design/arco-design-pro#45]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro@2.4.0
- **System:** mac
- **Browser:** chrome100.0.4896.60

## What is expected?
有正确的构建生产环境的 script

**Comment by Tenodec** [comment]
同问，vite 如何打包啊？？总不能跑个开发版本吧哈哈哈哈

**Comment by chenc041** [comment]
> 同问，vite 如何打包啊？？总不能跑个开发版本吧哈哈哈哈

就加个 `tsc && vite build` 这个命令就好了
tsc 校验下类型
vite build 构建生产资源

**Comment by Tenodec** [comment]
> > 同问，vite 如何打包啊？？总不能跑个开发版本吧哈哈哈哈
> 
> 就加个 `tsc && vite build` 这个命令就好了 tsc 校验下类型 vite build 构建生产资源

后来直接拷贝了vite的指令。开始以为像umi，有什么特殊的打包脚本
