### ISSUE TITLE
当进行菜单的快速切换时，控制台提示内存泄漏

### ISSUE THREAD

**Issue by MutongXiao** [arco-design/arco-design-pro#50]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro@2.4.0
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** https://github.com/arco-design/arco-design-pro/issues

## Extra info
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

## What is expected?
这是否是一个需要修复的bug

**Comment by muyu2019** [comment]
我也遇到过，这个bug不用修复，因为这个错误和框架没有关系。

**Comment by MutongXiao** [comment]
> 我也遇到过，这个bug不用修复，因为这个错误和框架没有关系。

那是什么原因造成的呢？我并没有对下载下来的代码进行任何改动，然后用chrome和edge浏览器直接运行，都会有这样的错误。我很想知道这其中的原因。 
Can't perform a React state update on an unmounted component, This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup functio（不能执行状态更新，在组件卸载的时候），这并不是某个页面的问题，似乎多个页面的卸载，也会有这样的问题
