### ISSUE TITLE
react 版本能否更换状态库而不是使用 redux ?

### ISSUE THREAD

**Issue by watsonhaw5566** [arco-design/arco-design-pro#58]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## 现有案例
https://umijs.org/zh-CN/plugins/plugin-model

## 预期解决问题
能否选择团队已有的 状态库 而不是统一使用 redux 。

**Comment by summeryio** [comment]
redux 挺好的，想换肯定要自己去配吧

**Comment by watsonhaw5566** [comment]
> redux 挺好的，想换肯定要自己去配吧

嗯，那我自己再缓缓，谢谢 @summeryio 兄弟
