### ISSUE TITLE
[react->arco pro] 怎么配置proxy

### ISSUE THREAD

**Issue by jamesz2011** [arco-design/arco-design-pro#59]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro@2.6.0
- **Browser:** chrome96.0.4664.45

**Comment by summeryio** [comment]
使用http-proxy-middleware

**Comment by yuhan0709** [comment]
hello～ `next` ，`vite`，`create-react-app`都是目前比较火的前端框架，proxy是常见配置可以看一下文档哦～

**Comment by gi19901212** [comment]
> 使用http-proxy-middleware
http-proxy-middleware似乎在arco-cli创建的项目中不生效，原因未知，使用在webpack.config.js 中增加proxy的方法是可行的。
