### ISSUE TITLE
使用 PermissionWrapper 组件包裹固定元素进行权限管理, 并设置backup属性. 渲染时会先闪现backup, 然后再展示期望的组件. 

### ISSUE THREAD

**Issue by lyqeyes** [arco-design/arco-design-pro#63]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro@2.6.0

## What is expected?
有权限时直接展示被包裹的组件, backup不要出现. 

## Steps to reproduce
1. PermissionWrapper 包裹组件, 并设置requiredPermissions 和 backup 属性.
2. 当前用户具备requiredPermissions声明的权限
3. 刷新页面
4. 先闪现了backup的内容, 然后再快速恢复到期望的内容

> 代码示例: 

`<PermissionWrapper
      requiredPermissions={[
        { resource: 'menu.list.searchTable', actions: ['write'] },
      ]}
      backup={
        <>
          <div>
            申请权限!!!申请权限!!!申请权限!!!申请权限!!!申请权限!!!
            <hr /> WWWWWWWWWWWWWWWWWWWWW
            <hr /> WWWWWWWWWWWWWWWWWWWWW
            <hr /> WWWWWWWWWWWWWWWWWWWWW
            <hr /> WWWWWWWWWWWWWWWWWWWWW
            <hr /> WWWWWWWWWWWWWWWWWWWWW
            <hr /> WWWWWWWWWWWWWWWWWWWWW
          </div>
        </>
      }
    >
    <Card>...</Card>
</PermissionWrapper>
`

![20220628145028](https://user-images.githubusercontent.com/9962597/176112632-d85d38e8-cf16-4f40-aeed-cba6a37bd678.gif)

**Comment by Gmengjie** [comment]
问题已定位，稍后提pr进行修复。
