### ISSUE TITLE
请问是否有计划出一套Pro Component 

### ISSUE THREAD

**Issue by lovesL** [arco-design/arco-design-pro#81]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## 现有案例
参考阿里的pro com

## 预期解决问题
请问是否有计划出一套Pro Component  我很细这种简约风格

**Comment by yuhan0709** [comment]
官方暂时没有计划推出，主要是不好把控业务场景跟组件的复杂程度。对于不同的业务场景封装统一的 ProComponent 开发成本跟用户上手成本也比较高。可以看下物料市场，根据自己特定业务自己封装一些物料～ 感谢共建
