### ISSUE TITLE
表格多选的时候如何获取整行数据

### ISSUE THREAD

**Issue by GGB321** [arco-design/arco-design-pro#85]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## What are the similar cases of this feature
大佬们，表格如何获取整行数据

## What problem does this feature solve?
大佬们，表格如何获取整行数据

**Comment by yuhan0709** [comment]
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/23137528/195261968-f3150fb0-311c-4740-9317-abee391c216c.png">
这个回调的第二个参数可以获取到 `rowSelect.onChange` 但需要开启受控
