### ISSUE TITLE
启动后没有样式

### ISSUE THREAD

**Issue by fengzhongye** [arco-design/arco-design-pro#89]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro@2.7.0
- **Framework version:** React
- **Browser:** chrome107.0.0.0

## Steps to reproduce
@arco-design/arco-cli 创建 React 项目成功后，启动无样式

![1668485702416](https://user-images.githubusercontent.com/4496435/201824986-38fc69d2-968c-4268-b4a3-accc3c351014.png)

**Comment by yuhan0709** [comment]
是 next 项目吗， next 项目在安装时默认是会全局引入样式的呀～ 可以把仓库发给我看下嘛

**Comment by yuhan0709** [comment]
simple-next 模版确实有这个问题，抱歉

**Comment by yuhan0709** [comment]
#78

**Comment by yuhan0709** [comment]
Resolved in #78

**Comment by HeiShuXianSheng** [comment]
> Resolved in #78

cra模板也是这个问题 : )

**Comment by zhengfc** [comment]
执行arco init ...没把这个样式拷贝过去还是没有，需要手动加上去才行

> Resolved in #78
