### ISSUE TITLE
使用cra模板创建项目的问题

### ISSUE THREAD

**Issue by HeiShuXianSheng** [arco-design/arco-design-pro#93]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro@2.7.0
- **Browser:** chrome107.0.0.0

-------
"arco-design-pro": "^2.7.0"

创建pro 选择 cra 模板的简单版（只包含一个基础页面）时：
1. window平台`npm i `时，`"prepare": "husky install && husky add .husky/pre-commit 'npm run pre-commit'"`报错，为了兼容win，建议单引号转义为双引号
2. 项目跑起来后登录页面的icon变得很大，丢失样式；

创建 cra 的完整版时：
上面第一第二依然存在；
3. 缺少dayjs依赖；需要开发者自己手动安装依赖。。。

**Comment by HeiShuXianSheng** [comment]
第二个样式丢失问题，暂时的解决办法是手动添加样式： https://github.com/arco-design/arco-design-pro/pull/78

**Comment by yuhan0709** [comment]
> 第二个样式丢失问题，暂时的解决办法是手动添加样式： #78

抱歉上次合并了并未发版，今天马上发个新版本～

**Comment by yuhan0709** [comment]
> 第二个样式丢失问题，暂时的解决办法是手动添加样式： #78

cra 没有引入样式文件是因为使用了 [ArcoWebpackPlugin](https://github.com/arco-design/arco-plugins/blob/main/packages/plugin-webpack-react/README.zh-CN.md) 可以直接实现样式按需加载的。
