### ISSUE TITLE
能否添加多页签功能

### ISSUE THREAD

**Issue by zssgitcn** [arco-design/arco-design-pro#98]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro/issues)

## 现有案例
arco-design-pro 的vue版本有实现该功能

## 预期解决问题
增加多页签功能

## 额外补充
我觉得多页签功能应该是一个比较刚需的需求，起码对于我或者说我所在的行业来说 是这样的

**Comment by yuhan0709** [comment]
暂时不会支持哈。
